### ISSUE TITLE
markdown 渲染 bug

### ISSUE THREAD

**Issue by vilic** [makeflow/librarian#10]
Source:

`JSON (**J**ava**S**cript **O**bject **N**otation)`

Rendered:

`JSON (J**avaScript **Object Notation)`

![image](https://user-images.githubusercontent.com/970430/44319433-52f5d300-a46e-11e8-9427-83c1e0f4c7e5.png)

**Comment by heikezy** [comment]
fixed at https://github.com/makeflow/librarian/commit/fb78c0b
